{'../ejabberd-dev/src/gen_mod', [{outdir, "../ejabberd-dev/ebin"},{i,"../ejabberd-dev/include"}]}.
{'src/mod_carboncopy',     [{outdir, "ebin"},{i,"../ejabberd-dev/include"},{i,"../../exmpp/include"}]}.
